# Generated by Django 4.0.4 on 2022-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/spinner', upload_to='courses/%Y/%m/%d/'),
        ),
    ]
